mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
        - ./data/mariadb:/var/lib/mysql
    env_file:
        - ./app/env/.env

nginx:
    build: ./nginx/
    expose:
        - 8081
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app
        
app:
    image: alpine:latest
    volumes:
        - ./app:/var/www/html
    command: "true"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql

varnish:
    build: ./varnish/
    ports:
        - 80:80
    links:
        - php
        - nginx
    volumes:
        - ./data/varnish:/var/lib/varnish